import { Footer } from '@widgets/footer/ui';
import { Header } from '@widgets/header/ui';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import './styles/index.scss';

const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
});

const aeonik = localFont({
	src: [
		{
			path: './fonts/Aeonik/Aeonik-Regular.otf',
			weight: '400',
			style: 'normal',
		},
	],
	variable: '--font-aeonik',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.variable} ${aeonik.variable} antialiased`}>
				<Header />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
